/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Checkin } from "./Checkin";
export * as factories from "./factories";
export { Checkin__factory } from "./factories/Checkin__factory";
